### ISSUE TITLE
How to address components in DSCR?

### ISSUE THREAD

**Issue by lucdekens** [vmware/dscr-for-vmware#7] opened 2018-12-16 21:26 UTC
Many vSphere components can be accessed via multiple paths.
For example a VM has a path in HostandCluster but also in VM.
The combination of these paths provide the unique location for an object.

How do we specify these different paths?
Shall these paths be keys, but perhaps not mandatory?
Do these paths belong in the BaseDsc class?

Please clarify before users start contributing, and each come up with their own solution.

**Comment by dmilov** [comment] 2018-12-17 08:47
There will be special base for inventory objects. It should provide key properties to identify inventory objects. Give us the time to design and add this base resource to enable contributing with inventory object resources.

Duplicate of #11

**Closed by dmilov** 2018-12-17 08:47 UTC
